# Generated by Django 5.1.9 on 2025-09-10 18:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_hourlyobsagg_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualObservationConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
            ],
            options={
                'verbose_name': 'Manual Observation Connection',
                'verbose_name_plural': 'Manual Observation Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='ManualObservationStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
            ],
            options={
                'verbose_name': 'Manual Observation Station Link',
                'verbose_name_plural': 'Manual Observation Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='ManualObservationStationLinkVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('obs_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Observation Parameter Unit')),
                ('station_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_collector_app_plugin.manualobservationstationlink')),
            ],
            options={
                'verbose_name': 'Manual Observation Variable Mapping',
                'verbose_name_plural': 'Manual Observation Variable Mappings',
            },
        ),
    ]
