# Generated by Django 5.1.9 on 2025-09-11 07:13

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_collector_app_plugin', '0002_manualobservationstationlinkobserver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualobservationstationlinkobserver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='CollectorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_time', models.DateTimeField()),
                ('observation_time', models.DateTimeField()),
                ('data', models.JSONField()),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='adl_collector_app_plugin.manualobservationstationlinkobserver')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='adl_collector_app_plugin.manualobservationstationlink')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorSubmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.FloatField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('submission', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='adl_collector_app_plugin.collectorsubmission')),
                ('variable_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adl_collector_app_plugin.manualobservationstationlinkvariablemapping')),
            ],
        ),
        migrations.AddIndex(
            model_name='collectorsubmission',
            index=models.Index(fields=['station_link', 'observation_time'], name='adl_collect_station_3ba825_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsubmission',
            index=models.Index(fields=['content_hash'], name='adl_collect_content_f933fe_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsubmission',
            index=models.Index(fields=['created_at'], name='adl_collect_created_fea470_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorsubmission',
            constraint=models.UniqueConstraint(fields=('observer', 'observation_time', 'content_hash'), name='uq_obs_time_payload'),
        ),
        migrations.AddIndex(
            model_name='collectorsubmissionrecord',
            index=models.Index(fields=['variable_mapping', 'is_processed'], name='adl_collect_variabl_1b76f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorsubmissionrecord',
            constraint=models.UniqueConstraint(fields=('submission', 'variable_mapping'), name='unique_mapping_per_submission'),
        ),
    ]
