# Generated by Django 5.1.9 on 2025-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_collector_app_plugin', '0005_manualobservationstationlinkvariablemapping_qc_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorsubmission',
            name='is_test_submission',
            field=models.BooleanField(default=False),
        ),
    ]
