# Generated by Django 6.0.5 on 2026-05-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_collector_app_plugin', '0006_collectorsubmission_is_test_submission'),
        ('core', '0042_alter_dataparameter_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynopMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('observation_time', models.DateTimeField(blank=True, help_text='Observation time extracted from the SYNOP message or provided by the submitter.', null=True)),
                ('raw_message', models.TextField(verbose_name='Raw SYNOP Message')),
                ('decoded_json', models.JSONField(help_text='Full pymetdecoder output stored for reference.', verbose_name='Decoded SYNOP')),
            ],
            options={
                'verbose_name': 'SYNOP Message',
                'verbose_name_plural': 'SYNOP Messages',
            },
        ),
        migrations.CreateModel(
            name='SynopParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm12_element_path', models.CharField(choices=[('air_temperature.value', 'Air Temperature (°C)'), ('dewpoint_temperature.value', 'Dew-Point Temperature (°C)'), ('wet_bulb_temperature.value', 'Wet-Bulb Temperature (°C)'), ('maximum_temperature.value', 'Maximum Temperature (°C)'), ('minimum_temperature.value', 'Minimum Temperature (°C)'), ('ground_minimum_temperature.value', 'Ground Minimum Temperature (°C)'), ('relative_humidity.value', 'Relative Humidity (%)'), ('station_pressure.value', 'Station Pressure (hPa)'), ('sea_level_pressure.value', 'Sea-Level Pressure (hPa)'), ('pressure_change.value', 'Pressure Change (hPa)'), ('pressure_tendency.change.value', 'Pressure Tendency — Change Amount (hPa)'), ('surface_wind.speed.value', 'Surface Wind Speed (m/s or kn)'), ('surface_wind.direction.value', 'Surface Wind Direction (degrees)'), ('highest_gust.speed.value', 'Highest Gust Speed (m/s or kn)'), ('highest_gust.direction.value', 'Highest Gust Direction (degrees)'), ('visibility.value', 'Visibility (m)'), ('lowest_cloud_base.min', 'Lowest Cloud-Base Height — lower bound (m)'), ('precipitation_s1.amount.value', 'Precipitation — Section 1 (mm)'), ('precipitation_s3.amount.value', 'Precipitation — Section 3 (mm)'), ('precipitation_24h.amount.value', 'Precipitation — 24-hour (mm)'), ('local_precipitation.amount.value', 'Local Precipitation Amount (mm)'), ('snow_fall.amount.value', 'Snowfall Amount (cm)'), ('sunshine.amount.value', 'Sunshine Duration (h)'), ('evapotranspiration.amount.value', 'Evapotranspiration (mm)'), ('temperature_change.value', 'Temperature Change (°C)'), ('ground_state.temperature.value', 'Ground-State — Surface Temperature (°C)'), ('sea_surface_temperature.value', 'Sea-Surface Temperature (°C)'), ('wind_waves.height.value', 'Wind Waves — Height (m)'), ('wind_waves.period.value', 'Wind Waves — Period (s)'), ('exact_obs_time.value', 'Exact Observation Time (minutes past hour)'), ('cloud_layer.0.cloud_height.value', 'Cloud Layer 1 — Base Height (m)'), ('cloud_layer.1.cloud_height.value', 'Cloud Layer 2 — Base Height (m)'), ('cloud_layer.2.cloud_height.value', 'Cloud Layer 3 — Base Height (m)'), ('cloud_layer.3.cloud_height.value', 'Cloud Layer 4 — Base Height (m)'), ('cloud_base_below_station.0.upper_surface_altitude.value', 'Cloud Base Below Station 1 — Upper Altitude (m)'), ('cloud_base_below_station.1.upper_surface_altitude.value', 'Cloud Base Below Station 2 — Upper Altitude (m)'), ('cloud_base_below_station.2.upper_surface_altitude.value', 'Cloud Base Below Station 3 — Upper Altitude (m)'), ('cloud_cover._code', 'Total Cloud Cover — N (WMO table 2700, oktas)'), ('cloud_types.low_cloud_type.value', 'Low Cloud Type — CL (WMO table 0513)'), ('cloud_types.middle_cloud_type.value', 'Middle Cloud Type — CM (WMO table 0515)'), ('cloud_types.high_cloud_type.value', 'High Cloud Type — CH (WMO table 0509)'), ('cloud_types.low_cloud_amount.value', 'Low Cloud Amount — Nh (oktas)'), ('lowest_cloud_base._code', 'Lowest Cloud-Base Height — WMO table code (table 1600)'), ('present_weather.value', 'Present Weather — ww (WMO table 4677 / 4680)'), ('pressure_tendency.tendency.value', 'Pressure Tendency Characteristic — a (WMO table 0200)'), ('visibility._code', 'Visibility — WMO table code (table 4377)'), ('ground_state.state.value', 'Ground State — E (WMO table 0901)'), ('ground_state_snow.state.value', "Ground State (Snow) — E' (WMO table 0975)"), ('ground_state_snow.depth.value', 'Snow Depth (cm)'), ('sea_state.value', 'Sea State (WMO table 3700)'), ('past_weather.0.value', 'Past Weather W1 (WMO table 4531, codes 0–9)'), ('past_weather.1.value', 'Past Weather W2 (WMO table 4531, codes 0–9)'), ('cloud_layer.0.cloud_cover._code', 'Cloud Layer 1 — Amount (WMO table 2700, oktas)'), ('cloud_layer.0.cloud_genus._code', 'Cloud Layer 1 — Genus (WMO table 0500)'), ('cloud_layer.0.cloud_height._code', 'Cloud Layer 1 — Height Code (WMO table 1677)'), ('cloud_layer.1.cloud_cover._code', 'Cloud Layer 2 — Amount (WMO table 2700, oktas)'), ('cloud_layer.1.cloud_genus._code', 'Cloud Layer 2 — Genus (WMO table 0500)'), ('cloud_layer.1.cloud_height._code', 'Cloud Layer 2 — Height Code (WMO table 1677)'), ('cloud_layer.2.cloud_cover._code', 'Cloud Layer 3 — Amount (WMO table 2700, oktas)'), ('cloud_layer.2.cloud_genus._code', 'Cloud Layer 3 — Genus (WMO table 0500)'), ('cloud_layer.2.cloud_height._code', 'Cloud Layer 3 — Height Code (WMO table 1677)'), ('cloud_layer.3.cloud_cover._code', 'Cloud Layer 4 — Amount (WMO table 2700, oktas)'), ('cloud_layer.3.cloud_genus._code', 'Cloud Layer 4 — Genus (WMO table 0500)'), ('cloud_layer.3.cloud_height._code', 'Cloud Layer 4 — Height Code (WMO table 1677)'), ('cloud_base_below_station.0.cloud_cover._code', 'Cloud Base Below Station 1 — Amount (WMO table 2700)'), ('cloud_base_below_station.0.description._code', 'Cloud Base Below Station 1 — Description (WMO table 0552)'), ('cloud_base_below_station.1.cloud_cover._code', 'Cloud Base Below Station 2 — Amount (WMO table 2700)'), ('cloud_base_below_station.1.description._code', 'Cloud Base Below Station 2 — Description (WMO table 0552)'), ('cloud_base_below_station.2.cloud_cover._code', 'Cloud Base Below Station 3 — Amount (WMO table 2700)'), ('cloud_base_below_station.2.description._code', 'Cloud Base Below Station 3 — Description (WMO table 0552)')], help_text="Dot-notation path into the pymetdecoder decoded dict. Physical quantities use the '.value' leaf (e.g. 'air_temperature.value'). Coded WMO parameters use '._code' or '.value' depending on the field (e.g. 'cloud_cover._code' for oktas, 'cloud_types.low_cloud_type.value' for CL). For range fields, '._code' is the WMO table index and '.min' is the lower bound in metres.", max_length=100, unique=True, verbose_name='FM12 Element Path')),
            ],
            options={
                'verbose_name': 'SYNOP Parameter Mapping',
                'verbose_name_plural': 'SYNOP Parameter Mappings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='collectorsubmission',
            name='uq_obs_time_payload',
        ),
        migrations.AddField(
            model_name='collectorsubmission',
            name='office_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Office Submitted By'),
        ),
        migrations.AddField(
            model_name='manualobservationconnection',
            name='enable_field_app',
            field=models.BooleanField(default=False, help_text='Show the PWA field observer app link for this connection.', verbose_name='Enable Field Observer App'),
        ),
        migrations.AddField(
            model_name='manualobservationconnection',
            name='enable_office_entry',
            field=models.BooleanField(default=False, help_text='Show office data entry and SYNOP links for this connection.', verbose_name='Enable Office Entry'),
        ),
        migrations.AddField(
            model_name='manualobservationstationlinkvariablemapping',
            name='show_in_direct_entry',
            field=models.BooleanField(default=True, help_text='If unchecked, this parameter will not appear in office/PWA/app direct-entry forms. Uncheck for SYNOP-decoded parameters that should not be entered manually.', verbose_name='Show in Direct Entry'),
        ),
        migrations.AlterField(
            model_name='collectorsubmission',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='adl_collector_app_plugin.manualobservationstationlinkobserver'),
        ),
        migrations.AddConstraint(
            model_name='collectorsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('observer__isnull', False)), fields=('observer', 'observation_time', 'content_hash'), name='uq_obs_time_payload'),
        ),
        migrations.AddField(
            model_name='synopmessage',
            name='station_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='synop_messages', to='adl_collector_app_plugin.manualobservationstationlink'),
        ),
        migrations.AddField(
            model_name='synopmessage',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synop_source', to='adl_collector_app_plugin.collectorsubmission'),
        ),
        migrations.AddField(
            model_name='synopmessage',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synop_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='synopparametermapping',
            name='adl_parameter',
            field=models.OneToOneField(help_text='Each ADL parameter may only appear in one FM12 mapping.', on_delete=django.db.models.deletion.CASCADE, related_name='synop_mapping', to='core.dataparameter', verbose_name='ADL Parameter'),
        ),
        migrations.AddField(
            model_name='synopparametermapping',
            name='source_unit',
            field=models.ForeignKey(help_text="Unit in which pymetdecoder returns this element's value.", on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Source Unit'),
        ),
        migrations.AddIndex(
            model_name='synopmessage',
            index=models.Index(fields=['station_link', 'observation_time'], name='adl_collect_station_bfd41d_idx'),
        ),
        migrations.AddIndex(
            model_name='synopmessage',
            index=models.Index(fields=['received_at'], name='adl_collect_receive_c916eb_idx'),
        ),
    ]
