# Generated by Django 6.0.5 on 2026-05-21 10:03

import adl_collector_app_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_collector_app_plugin', '0007_synopmessage_synopparametermapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualobservationstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='The date to start collection data for the first collection. Ignored if any data has been collected already for this station', null=True, validators=[adl_collector_app_plugin.validators.validate_start_date], verbose_name='Initial Collection start date'),
        ),
    ]
