# Generated by Django 6.0.7 on 2026-08-19 16:17

import adl_collector_app_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_collector_app_plugin', '0008_manualobservationstationlink_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualobservationstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Collection never starts before this date. On the first run it is the start of the backfill; afterwards, moving it forward past the latest saved record skips the gap. Leave empty to start from the last hour.', null=True, validators=[adl_collector_app_plugin.validators.validate_start_date], verbose_name='Collection Start Date'),
        ),
    ]
