from typing import Optional

# ---------------------------------------------------------------------------
# FM12 parameter metadata for the SYNOP Setup Wizard.
#
# Each entry describes one FM12 element path:
#   path                  — dot-notation path used in SynopParameterMapping
#   label                 — human-readable display name (without unit suffix)
#   suggested_unit_symbol — pint symbol that pymetdecoder returns; None for coded params
#   is_coded              — True if value is a WMO lookup-table integer (no unit conversion)
#   wmo_code_table        — WMO table ID string for coded params, else None
#   common_adl_names      — candidate DataParameter.name values for auto-matching
#   adl_category          — default DataParameter category if creating new
# ---------------------------------------------------------------------------

SYNOP_COMMON_PARAMETERS: list[dict] = [
    {
        "path": "air_temperature.value",
        "label": "Air Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["air_temperature", "temperature", "temp", "ta", "air temp"],
        "adl_category": "meteorological",
    },
    {
        "path": "dewpoint_temperature.value",
        "label": "Dew-Point Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["dewpoint", "dew_point", "dew_point_temperature", "td"],
        "adl_category": "meteorological",
    },
    {
        "path": "relative_humidity.value",
        "label": "Relative Humidity",
        "suggested_unit_symbol": "%",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["relative_humidity", "humidity", "rh"],
        "adl_category": "meteorological",
    },
    {
        "path": "station_pressure.value",
        "label": "Station Pressure",
        "suggested_unit_symbol": "hPa",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["station_pressure", "pressure", "p0"],
        "adl_category": "meteorological",
    },
    {
        "path": "sea_level_pressure.value",
        "label": "Sea-Level Pressure",
        "suggested_unit_symbol": "hPa",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["sea_level_pressure", "mslp", "slp", "qnh"],
        "adl_category": "meteorological",
    },
    {
        "path": "surface_wind.speed.value",
        "label": "Wind Speed",
        "suggested_unit_symbol": "m/s",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["wind_speed", "wind speed", "ff"],
        "adl_category": "meteorological",
    },
    {
        "path": "surface_wind.direction.value",
        "label": "Wind Direction",
        "suggested_unit_symbol": "deg",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["wind_direction", "wind direction", "dd"],
        "adl_category": "meteorological",
    },
    {
        "path": "visibility.value",
        "label": "Visibility",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["visibility", "vv", "vis"],
        "adl_category": "meteorological",
    },
    {
        "path": "precipitation_s1.amount.value",
        "label": "Precipitation (Section 1)",
        "suggested_unit_symbol": "mm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["precipitation", "rainfall", "rain", "rr", "precip"],
        "adl_category": "meteorological",
    },
    {
        "path": "precipitation_24h.amount.value",
        "label": "Precipitation 24h",
        "suggested_unit_symbol": "mm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["precipitation_24h", "rain_24h", "daily_rain", "rr24"],
        "adl_category": "meteorological",
    },
    {
        "path": "maximum_temperature.value",
        "label": "Maximum Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["maximum_temperature", "max_temp", "tmax", "tx"],
        "adl_category": "meteorological",
    },
    {
        "path": "minimum_temperature.value",
        "label": "Minimum Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["minimum_temperature", "min_temp", "tmin", "tn"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_cover._code",
        "label": "Total Cloud Cover (oktas)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_cover", "cloud cover", "total_cloud", "n"],
        "adl_category": "meteorological",
    },
    {
        "path": "present_weather.value",
        "label": "Present Weather",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "4677",
        "common_adl_names": ["present_weather", "weather", "ww"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_types.low_cloud_type.value",
        "label": "Low Cloud Type (CL)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0513",
        "common_adl_names": ["low_cloud_type", "cl", "low cloud"],
        "adl_category": "meteorological",
    },
]

SYNOP_EXTENDED_PARAMETERS: list[dict] = [
    {
        "path": "wet_bulb_temperature.value",
        "label": "Wet-Bulb Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["wet_bulb_temperature", "wet_bulb", "tw"],
        "adl_category": "meteorological",
    },
    {
        "path": "ground_minimum_temperature.value",
        "label": "Ground Minimum Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["ground_minimum_temperature", "ground_min_temp", "tg"],
        "adl_category": "meteorological",
    },
    {
        "path": "pressure_change.value",
        "label": "Pressure Change (3h)",
        "suggested_unit_symbol": "hPa",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["pressure_change", "dp3h"],
        "adl_category": "meteorological",
    },
    {
        "path": "pressure_tendency.change.value",
        "label": "Pressure Tendency — Change Amount",
        "suggested_unit_symbol": "hPa",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["pressure_tendency_change", "ppp"],
        "adl_category": "meteorological",
    },
    {
        "path": "highest_gust.speed.value",
        "label": "Highest Gust Speed",
        "suggested_unit_symbol": "m/s",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["gust_speed", "wind_gust", "gust"],
        "adl_category": "meteorological",
    },
    {
        "path": "highest_gust.direction.value",
        "label": "Highest Gust Direction",
        "suggested_unit_symbol": "deg",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["gust_direction", "wind_gust_direction"],
        "adl_category": "meteorological",
    },
    {
        "path": "lowest_cloud_base.min",
        "label": "Lowest Cloud-Base Height (lower bound)",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_base_height", "cloud_base", "h"],
        "adl_category": "meteorological",
    },
    {
        "path": "precipitation_s3.amount.value",
        "label": "Precipitation (Section 3)",
        "suggested_unit_symbol": "mm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["precipitation_s3"],
        "adl_category": "meteorological",
    },
    {
        "path": "local_precipitation.amount.value",
        "label": "Local Precipitation Amount",
        "suggested_unit_symbol": "mm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["local_precipitation"],
        "adl_category": "meteorological",
    },
    {
        "path": "snow_fall.amount.value",
        "label": "Snowfall Amount",
        "suggested_unit_symbol": "cm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["snowfall", "snow", "snow_depth"],
        "adl_category": "meteorological",
    },
    {
        "path": "sunshine.amount.value",
        "label": "Sunshine Duration",
        "suggested_unit_symbol": "h",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["sunshine_duration", "sunshine", "ss"],
        "adl_category": "meteorological",
    },
    {
        "path": "evapotranspiration.amount.value",
        "label": "Evapotranspiration",
        "suggested_unit_symbol": "mm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["evapotranspiration", "evapo", "et"],
        "adl_category": "meteorological",
    },
    {
        "path": "temperature_change.value",
        "label": "Temperature Change",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["temperature_change"],
        "adl_category": "meteorological",
    },
    {
        "path": "ground_state.temperature.value",
        "label": "Ground-State Surface Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["ground_temperature", "surface_temperature", "tss"],
        "adl_category": "meteorological",
    },
    {
        "path": "sea_surface_temperature.value",
        "label": "Sea-Surface Temperature",
        "suggested_unit_symbol": "degC",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["sea_surface_temperature", "sst"],
        "adl_category": "meteorological",
    },
    {
        "path": "wind_waves.height.value",
        "label": "Wind Waves — Height",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["wave_height", "wind_wave_height"],
        "adl_category": "meteorological",
    },
    {
        "path": "wind_waves.period.value",
        "label": "Wind Waves — Period",
        "suggested_unit_symbol": "s",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["wave_period", "wind_wave_period"],
        "adl_category": "meteorological",
    },
    {
        "path": "exact_obs_time.value",
        "label": "Exact Observation Time (minutes past hour)",
        "suggested_unit_symbol": "min",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["exact_obs_time"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.0.cloud_height.value",
        "label": "Cloud Layer 1 — Base Height",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_layer_1_height"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.1.cloud_height.value",
        "label": "Cloud Layer 2 — Base Height",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_layer_2_height"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.2.cloud_height.value",
        "label": "Cloud Layer 3 — Base Height",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_layer_3_height"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.3.cloud_height.value",
        "label": "Cloud Layer 4 — Base Height",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_layer_4_height"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.0.upper_surface_altitude.value",
        "label": "Cloud Base Below Station 1 — Upper Altitude",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_base_below_station_1"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.1.upper_surface_altitude.value",
        "label": "Cloud Base Below Station 2 — Upper Altitude",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_base_below_station_2"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.2.upper_surface_altitude.value",
        "label": "Cloud Base Below Station 3 — Upper Altitude",
        "suggested_unit_symbol": "m",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["cloud_base_below_station_3"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_types.middle_cloud_type.value",
        "label": "Middle Cloud Type (CM)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0515",
        "common_adl_names": ["middle_cloud_type", "cm", "middle cloud"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_types.high_cloud_type.value",
        "label": "High Cloud Type (CH)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0509",
        "common_adl_names": ["high_cloud_type", "ch", "high cloud"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_types.low_cloud_amount.value",
        "label": "Low Cloud Amount — Nh (oktas)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["low_cloud_amount", "nh"],
        "adl_category": "meteorological",
    },
    {
        "path": "lowest_cloud_base._code",
        "label": "Lowest Cloud-Base Height — WMO code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "1600",
        "common_adl_names": ["cloud_base_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "pressure_tendency.tendency.value",
        "label": "Pressure Tendency Characteristic (a)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0200",
        "common_adl_names": ["pressure_tendency_characteristic", "a_tendency"],
        "adl_category": "meteorological",
    },
    {
        "path": "visibility._code",
        "label": "Visibility — WMO code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "4377",
        "common_adl_names": ["visibility_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "ground_state.state.value",
        "label": "Ground State (E)",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0901",
        "common_adl_names": ["ground_state", "e_ground"],
        "adl_category": "meteorological",
    },
    {
        "path": "ground_state_snow.state.value",
        "label": "Ground State Snow (E')",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0975",
        "common_adl_names": ["ground_state_snow"],
        "adl_category": "meteorological",
    },
    {
        "path": "ground_state_snow.depth.value",
        "label": "Snow Depth",
        "suggested_unit_symbol": "cm",
        "is_coded": False,
        "wmo_code_table": None,
        "common_adl_names": ["snow_depth", "sss"],
        "adl_category": "meteorological",
    },
    {
        "path": "sea_state.value",
        "label": "Sea State",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "3700",
        "common_adl_names": ["sea_state"],
        "adl_category": "meteorological",
    },
    {
        "path": "past_weather.0.value",
        "label": "Past Weather W1",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "4531",
        "common_adl_names": ["past_weather_w1", "w1"],
        "adl_category": "meteorological",
    },
    {
        "path": "past_weather.1.value",
        "label": "Past Weather W2",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "4531",
        "common_adl_names": ["past_weather_w2", "w2"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.0.cloud_cover._code",
        "label": "Cloud Layer 1 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_layer_1_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.0.cloud_genus._code",
        "label": "Cloud Layer 1 — Genus",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0500",
        "common_adl_names": ["cloud_layer_1_genus"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.0.cloud_height._code",
        "label": "Cloud Layer 1 — Height Code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "1677",
        "common_adl_names": ["cloud_layer_1_height_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.1.cloud_cover._code",
        "label": "Cloud Layer 2 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_layer_2_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.1.cloud_genus._code",
        "label": "Cloud Layer 2 — Genus",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0500",
        "common_adl_names": ["cloud_layer_2_genus"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.1.cloud_height._code",
        "label": "Cloud Layer 2 — Height Code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "1677",
        "common_adl_names": ["cloud_layer_2_height_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.2.cloud_cover._code",
        "label": "Cloud Layer 3 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_layer_3_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.2.cloud_genus._code",
        "label": "Cloud Layer 3 — Genus",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0500",
        "common_adl_names": ["cloud_layer_3_genus"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.2.cloud_height._code",
        "label": "Cloud Layer 3 — Height Code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "1677",
        "common_adl_names": ["cloud_layer_3_height_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.3.cloud_cover._code",
        "label": "Cloud Layer 4 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_layer_4_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.3.cloud_genus._code",
        "label": "Cloud Layer 4 — Genus",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0500",
        "common_adl_names": ["cloud_layer_4_genus"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_layer.3.cloud_height._code",
        "label": "Cloud Layer 4 — Height Code",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "1677",
        "common_adl_names": ["cloud_layer_4_height_code"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.0.cloud_cover._code",
        "label": "Cloud Base Below Station 1 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_base_below_station_1_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.0.description._code",
        "label": "Cloud Base Below Station 1 — Description",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0552",
        "common_adl_names": ["cloud_base_below_station_1_description"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.1.cloud_cover._code",
        "label": "Cloud Base Below Station 2 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_base_below_station_2_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.1.description._code",
        "label": "Cloud Base Below Station 2 — Description",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0552",
        "common_adl_names": ["cloud_base_below_station_2_description"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.2.cloud_cover._code",
        "label": "Cloud Base Below Station 3 — Amount",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "2700",
        "common_adl_names": ["cloud_base_below_station_3_amount"],
        "adl_category": "meteorological",
    },
    {
        "path": "cloud_base_below_station.2.description._code",
        "label": "Cloud Base Below Station 3 — Description",
        "suggested_unit_symbol": None,
        "is_coded": True,
        "wmo_code_table": "0552",
        "common_adl_names": ["cloud_base_below_station_3_description"],
        "adl_category": "meteorological",
    },
]

_COMMON_PATHS = {p["path"] for p in SYNOP_COMMON_PARAMETERS}
ALL_SYNOP_PARAMETERS = SYNOP_COMMON_PARAMETERS + SYNOP_EXTENDED_PARAMETERS


def suggest_adl_parameter(fm12_meta: dict) -> Optional["DataParameter"]:  # noqa: F821
    """
    Try to find an existing DataParameter that plausibly matches this FM12 element.
    Tries each name in common_adl_names via case-insensitive icontains.
    For coded params, also requires is_coded=True on the parameter.
    Returns the first match, or None.
    """
    from adl.core.models import DataParameter
    
    qs = DataParameter.objects.select_related("unit")
    if fm12_meta.get("is_coded"):
        qs = qs.filter(is_coded=True)
        if fm12_meta.get("wmo_code_table"):
            exact = qs.filter(wmo_code_table=fm12_meta["wmo_code_table"]).first()
            if exact:
                return exact
    
    for name in fm12_meta.get("common_adl_names", []):
        match = qs.filter(name__icontains=name).first()
        if match:
            return match
    
    return None


def get_or_suggest_unit(symbol: str) -> Optional["Unit"]:  # noqa: F821
    """Return the first Unit matching the given pint symbol, or None."""
    from adl.core.models import Unit
    return Unit.objects.filter(symbol=symbol).first()


def count_mapped_common() -> int:
    """Return how many of the 15 common FM12 paths have a global SynopParameterMapping row."""
    from .models import SynopParameterMapping
    mapped = set(SynopParameterMapping.objects.values_list("fm12_element_path", flat=True))
    return len(_COMMON_PATHS & mapped)


# Lookup dict: fm12_element_path → metadata entry (used by auto-sync helper)
_path_to_meta: dict = {
    m["path"]: m for m in SYNOP_COMMON_PARAMETERS + SYNOP_EXTENDED_PARAMETERS
}
